### ISSUE TITLE
fallait pas m'inviter ^^

### ISSUE THREAD

**Issue by NyanVivi** [crep4ever/bloc#1]
Je propose qu'on mette ca en fond de site, avec une douce musique pour souhaiter la bienvenue aux visiteurs.

http://www.superbwallpapers.com/meme/nyan-cats-9994/

Romain, c'est grumpy gaufre
Pierre, tu veux etre lequel ? le dernier, on dirait qu'il a une griffe qui dépasse ?

**Comment by crep4ever** [comment]
grumpy gaufre ... bien trouvé ^^
